    drop database pessem3;

    create database pessem3;

    use pessem3;


CREATE TABLE DEMO(
    NUM INT,
    NAME VARCHAR(20),
    PRIMARY KEY(NUM)
);

INSERT INTO DEMO VALUES(1, 'PRADEEP');
INSERT INTO DEMO VALUES(2, 'LOLA');
INSERT INTO DEMO VALUES(3, 'MIA');
INSERT INTO DEMO VALUES(4, 'LOAS');
INSERT INTO DEMO VALUES(14, 'LOAS');
INSERT INTO DEMO VALUES(5, 'MIAN');
INSERT INTO DEMO VALUES(6, 'LOLAAS');
INSERT INTO DEMO VALUES(7, 'BOKA');
INSERT INTO DEMO VALUES(8, 'MIANIS');