drop database pessem3;

create database pessem3;

use pessem3;

CREATE TABLE Dept(
    sub_ssn INT,
    dept_name VARCHAR(20),
    PRIMARY KEY (sub_ssn)
);

CREATE TABLE EMPLOYEE(
    e_id INT,
    e_ssn INT,
    e_name VARCHAR(20),
    sub_ssn INT,
    e_salary INT,
    PRIMARY KEY (e_id),
    FOREIGN KEY (sub_ssn) REFERENCES Dept (sub_ssn)
);

INSERT INTO Dept VALUES (1, 'ACC');
INSERT INTO Dept VALUES (2, 'DEV');

INSERT INTO EMPLOYEE VALUES (1, 1, 'MIAMOR', 1, 10000);
INSERT INTO EMPLOYEE VALUES (2, 1, 'HOLA', 1, 2000);
INSERT INTO EMPLOYEE VALUES (3, 1, 'ISO', 1, 123);
INSERT INTO EMPLOYEE VALUES (4, 1, 'LOLA', 1, 1233);
INSERT INTO EMPLOYEE VALUES (5, 1, 'KITU', 1, 1233244);
INSERT INTO EMPLOYEE VALUES (6, 1, 'LIK', 1, 878);
INSERT INTO EMPLOYEE VALUES (7, 1, 'AS', 1, 213321);
INSERT INTO EMPLOYEE VALUES (8, 1, 'JIDSNJAK', 1, 5443);
INSERT INTO EMPLOYEE VALUES (9, 1, 'JINJAFDK', 1, 90000);
INSERT INTO EMPLOYEE VALUES (10, 1, 'JINASDLKMJAK', 1, 2198);
INSERT INTO EMPLOYEE VALUES (11, 1, 'JIJAK', 1, 1111);

CREATE TABLE DEPENDANT(
    e_id INT,
    DEPENDANT_NAME VARCHAR(30)
);

INSERT INTO DEPENDANT VALUES (10, 'MINO');
INSERT INTO DEPENDANT VALUES (11, 'LOLA');
INSERT INTO DEPENDANT VALUES (10, 'SKD');