drop database pessem3;

create database pessem3;

use pessem3;

CREATE TABLE EMPLOYEE(
    E_NAME VARCHAR(30),
    DEPT_NAME VARCHAR(30),
    SSN INT,
    SALARY INT,
    SUPER_SSN INT,
    PRIMARY KEY (SSN),
    FOREIGN KEY (SUPER_SSN) REFERENCES EMPLOYEE (SSN)
);

INSERT INTO EMPLOYEE values ('PRADEEP', 'DEV', 1, 1000000, 1);
INSERT INTO EMPLOYEE values ('PRADEEP', 'ACC', 2, 1000000, 1);
INSERT INTO EMPLOYEE values ('PRADEEP', 'DEV', 3, 1000000, 1);
INSERT INTO EMPLOYEE values ('PRADEEP', 'DEV', 4, 1000000, 1);